modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="limitedspectator"
version="1.21.1-1.1.0-beta"
displayName="Limited Spectator"
description="Fully configurable spectator mode with flight, distance limits, and customizable restrictions (BETA)"
authors="Karashi"
side="BOTH"

[[dependencies.limitedspectator]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.limitedspectator]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"