modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="limitedspectator"
version="1.21.1-1.0.2"
displayName="Limited Spectator"
description="Alternate spectator mode with flight, collisions and invulnerability"
authors="Karashi"
side="BOTH"

[[dependencies.limitedspectator]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.limitedspectator]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"